spring.application.name=kairo

server.port=3000
server.servlet.contextPath=/kairo

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.schema=${FLYWAY_SCHEMA_NAME}